# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Shipeng Yan"
title:              "Shipeng Yan"
description:        "Shipeng Yan"


# URL
url:                http://kordinglab.github.io
baseurl:
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "Home"
    href:           "/"
  # - name:           "about"
    # href:           "/about"
  - name:           "Publications"
    href:           "/publication"
  - name:           "Git"
    href:           "https://github.com/Rhyssiyan"
  - name:           "Google Scholar"
    href:           "https://scholar.google.com/citations?user=oYILsyoAAAAJ&hl=en"
  # - name:           "people"
    # href:           "/people"
  # - name:           "blog"
    # href:           "/blog"
  # - name:           "resources"
    # href:           "/resources"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: False
    permalink: /people/:title/index.html
